version: '2'
services:
    sampleelasticsearch-elasticsearch:
        container_name: sampleelasticsearch-elasticsearch
        image: elasticsearch:1.7.5
        # volumes:
        #     - ~/volumes/jhipster/sampleElasticSearch/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
