version: '2'
services:
    jhipsterelasticsearchsampleapplication-elasticsearch:
        container_name: jhipsterelasticsearchsampleapplication-elasticsearch
        image: elasticsearch:1.7.5
        # volumes:
        #     - ~/volumes/jhipster/jhipsterElasticsearchSampleApplication/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
